import React from 'react';
import { Layout } from '../Layout';
import * as Styles from '../../styles/GlobalStyles';

export const PrivacyPolicy: React.FC<{
	pageColorTheme: 'dark' | 'light';
	setPageColorTheme: React.Dispatch<React.SetStateAction<'dark' | 'light'>>;
}> = ({ pageColorTheme, setPageColorTheme }) => {
	return (
		<Layout
			pageColorTheme={pageColorTheme}
			setPageColorTheme={setPageColorTheme}
		>
			<Styles.About.Container>
				<h1>Privacy Policy</h1>
				<hr />
				This privacy policy outlines how any data that may be collected during
				your visit is handled.
				<br />
				<h2>Data Collection</h2>
				<hr />
				This website does not collect any personal data or any other data from
				users. Your browsing behavior, preferences, or usage patterns are not
				tracked. The only data that may be processed during your visit is
				related to the calculations performed by our calculator based on the
				user's interactions with the interface. <br />
				<h2>Data Storage</h2> <hr />
				Any data generated by the calculator or any other user input are not
				stored. The calculations are performed locally within your browser and
				are not transmitted to or stored on our servers. <br />
				<h2>Third-Party Services</h2> <hr />
				No third-party services or plugins that may collect data from users are
				used. This website is self-contained and does not rely on external
				services for functionality. <br />
				<h2>Cookies</h2> <hr />
				This website does not use cookies for tracking purposes. However, please
				note that certain technologies such as RTK Query may cache fetched data
				to improve performance. This cached data is stored locally within your
				browser and does not contain any personally identifiable information.{' '}
				<br />
				<h2>Hosting Provider</h2> <hr />
				This website is hosted on Fly.io, a third-party hosting provider. While
				this website do not directly control the data handling practices of
				Fly.io, This provider was chosen based on its commitment to privacy and
				security.
				<br />
				<h2>Updates to this Privacy Policy</h2> <hr />
				This privacy policy may be updated from time to time to reflect changes
				in our practices or for other operational, legal, or regulatory reasons.
				We encourage you to review this privacy policy periodically for any
				updates. <br />
				<h2>Contact Us</h2> <hr />
				If you have any questions or concerns about this privacy policy or our
				data practices, please contact us at [palwflydev.admn@gmail.com].
			</Styles.About.Container>
		</Layout>
	);
};
